//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seratio.Platform.ICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailPolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RetailPolicy()
        {
            this.AcceptedRetailPolicies = new HashSet<AcceptedRetailPolicy>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> RequiredCoinID { get; set; }
        public Nullable<int> ProcessedBy { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PolicyType { get; set; }
        public Nullable<decimal> MinSESCore { get; set; }
        public Nullable<decimal> MaxSEScore { get; set; }
        public Nullable<decimal> RequiredCoinQty { get; set; }
        public string DiscountMode { get; set; }
        public decimal DiscountValue { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<System.DateTime> RejectedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsDataActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcceptedRetailPolicy> AcceptedRetailPolicies { get; set; }
        public virtual Coin Coin { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
