//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seratio.Blockchain.Sandbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWalletHistory
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int SessionID { get; set; }
        public string OldWalletAddress { get; set; }
        public string NewWalletAddress { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserSession UserSession { get; set; }
    }
}
