//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seratio.News.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweet
    {
        public int ID { get; set; }
        public int AccountID { get; set; }
        public long TweetID { get; set; }
        public string Text { get; set; }
        public string Image { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual TwitterAccount TwitterAccount { get; set; }
    }
}
