//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seratio.Blockchain.Sandbox.Models
{
    using System;

    public partial class ActivityNotification
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> RelatedItemID { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public System.DateTime Time { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ReadOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
