//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seratio.Blockchain.Sandbox.Models
{
    using System;

    public partial class AdministratorSession
    {
        public int ID { get; set; }
        public int AdministratorID { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.Guid> Token { get; set; }
        public bool IsActive { get; set; }
        public bool HasTerminated { get; set; }
        public bool IsDataActive { get; set; }
    
        public virtual Administrator Administrator { get; set; }
    }
}
