//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seratio.Blockchain.Sandbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequest
    {
        public int ID { get; set; }
        public int CoinID { get; set; }
        public int RequestedByID { get; set; }
        public int PayerID { get; set; }
        public Nullable<int> WalletTransactionID { get; set; }
        public string Type { get; set; }
        public Nullable<int> RelatedItemID { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual WalletTransaction WalletTransaction { get; set; }
        public virtual Coin Coin { get; set; }
    }
}
