//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seratio.Blockchain.Sandbox.Models
{
    using System;

    public partial class Request
    {
        public int ID { get; set; }
        public int SenderID { get; set; }
        public string Recipient { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public bool HasDownloaded { get; set; }
        public bool HasRejected { get; set; }
        public System.DateTime SentOn { get; set; }
        public Nullable<System.DateTime> RespondedOn { get; set; }
        public bool IsDataActive { get; set; }
    
        public virtual User User { get; set; }
    }
}
