//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seratio.Blockchain.Sandbox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AcceptedRetailPolicies = new HashSet<AcceptedRetailPolicy>();
            this.AcceptedSocialActivities = new HashSet<AcceptedSocialActivity>();
            this.ActivityNotifications = new HashSet<ActivityNotification>();
            this.CollectedVouchers = new HashSet<CollectedVoucher>();
            this.FailedForgotPasswordAttempts = new HashSet<FailedForgotPasswordAttempt>();
            this.FailedSignInAttempts = new HashSet<FailedSignInAttempt>();
            this.FailedWalletTransactionAttempts = new HashSet<FailedWalletTransactionAttempt>();
            this.Investments = new HashSet<Investment>();
            this.MCRTokenInvestments = new HashSet<MCRTokenInvestment>();
            this.ModuleAccessRequests = new HashSet<ModuleAccessRequest>();
            this.ModuleAccessRequests1 = new HashSet<ModuleAccessRequest>();
            this.PaymentRequests = new HashSet<PaymentRequest>();
            this.PaymentRequests1 = new HashSet<PaymentRequest>();
            this.QRLogins = new HashSet<QRLogin>();
            this.Requests = new HashSet<Request>();
            this.RetailPolicies = new HashSet<RetailPolicy>();
            this.RetailPolicies1 = new HashSet<RetailPolicy>();
            this.SERTokenInvestments = new HashSet<SERTokenInvestment>();
            this.SocialActivities = new HashSet<SocialActivity>();
            this.SocialActivities1 = new HashSet<SocialActivity>();
            this.StoredSocialValues = new HashSet<StoredSocialValue>();
            this.UserSessions = new HashSet<UserSession>();
            this.UserWalletHistories = new HashSet<UserWalletHistory>();
            this.WalletTransactions = new HashSet<WalletTransaction>();
            this.Coins = new HashSet<Coin>();
            this.MCRAllocations = new HashSet<MCRAllocation>();
            this.MCRTransfers = new HashSet<MCRTransfer>();
            this.MCRTransfers1 = new HashSet<MCRTransfer>();
        }
    
        public int ID { get; set; }
        public byte[] AuthString { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.Guid AutoLoginToken { get; set; }
        public string Gender { get; set; }
        public string PostalCode { get; set; }
        public string Position { get; set; }
        public string WalletAddress { get; set; }
        public Nullable<System.Guid> ForgotPasswordToken { get; set; }
        public string Organization { get; set; }
        public string NickName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> EmailVerificationToken { get; set; }
        public Nullable<decimal> SE { get; set; }
        public bool IsEmailVerified { get; set; }
        public string AssetTransactionCriteria { get; set; }
        public Nullable<decimal> AssetTransactionCriteriaValue { get; set; }
        public Nullable<System.DateTime> EmailVerifiedOn { get; set; }
        public bool IsSearchable { get; set; }
        public bool IsSuperAdmin { get; set; }
        public string SaftyQuestion { get; set; }
        public byte[] SaftyAnswer { get; set; }
        public bool ShouldAllowSignInWithQR { get; set; }
        public bool AllowEmailNotifications { get; set; }
        public bool EnableTwoFactorAuthentication { get; set; }
        public bool IsBlockedWallet { get; set; }
        public string TwoFAKey { get; set; }
        public string ReferralSource { get; set; }
        public string WalletPassPhrase { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsDataActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcceptedRetailPolicy> AcceptedRetailPolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcceptedSocialActivity> AcceptedSocialActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityNotification> ActivityNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectedVoucher> CollectedVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FailedForgotPasswordAttempt> FailedForgotPasswordAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FailedSignInAttempt> FailedSignInAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FailedWalletTransactionAttempt> FailedWalletTransactionAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Investment> Investments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCRTokenInvestment> MCRTokenInvestments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleAccessRequest> ModuleAccessRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleAccessRequest> ModuleAccessRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequest> PaymentRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequest> PaymentRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QRLogin> QRLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetailPolicy> RetailPolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetailPolicy> RetailPolicies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERTokenInvestment> SERTokenInvestments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialActivity> SocialActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialActivity> SocialActivities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoredSocialValue> StoredSocialValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSession> UserSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserWalletHistory> UserWalletHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalletTransaction> WalletTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coin> Coins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCRAllocation> MCRAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCRTransfer> MCRTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCRTransfer> MCRTransfers1 { get; set; }
    }
}
